import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const root=path.resolve(new URL("..",import.meta.url).pathname);
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const html=read("real-estate/index.html");
const css=read("real-estate/style.css");
const main=read("real-estate/main.js");
const schema=read("real-estate/schema.js");
const index=read("index.html");
const api=read("workers/api/src/index.js");
const sql=read("workers/api/schema.sql");
const sw=read("sw.js");
const manifest=JSON.parse(read("manifest.webmanifest"));
assert.match(html,/<meta name="color-scheme" content="light">/);
assert.match(html,/Content-Security-Policy/);
assert.match(html,/connect-src 'none'/);
assert.doesNotMatch(html,/\sstyle\s*=/i);
assert.match(html,/id="contractForm"/);
assert.match(html,/id="status" role="status" aria-live="polite"/);
assert.match(html,/bithome/);
assert.match(css,/prefers-reduced-motion/);
assert.match(css,/prefers-contrast:more/);
assert.match(css,/safe-area-inset/);
assert.match(main,/aria-describedby/);
assert.match(main,/aria-invalid/);
assert.match(main,/textContent=message/);
assert.match(main,/textContent=text/);
assert.match(main,/DRAFT_UNVERIFIED/);
assert.doesNotMatch(main,/fetch\(/);
assert.match(schema,/bitcoin_mainnet/);
assert.match(schema,/multisigArbitrator/);
assert.match(schema,/BigInt/);
assert.match(api,/realEstateCaseRoute/);
assert.match(api,/FROM real_estate_cases WHERE id = \? AND user_id = \?/);
assert.match(api,/Object.keys\(body\).some\(key => !allowed.has\(key\)\)/);
assert.match(sql,/CREATE TABLE IF NOT EXISTS real_estate_cases/);
assert.match(index,/class="bithome-portal"/);
assert.match(index,/real-estate\/index.html/);
assert.equal(manifest.start_url,"./real-estate/");
assert.equal(manifest.display,"standalone");
assert.ok(manifest.icons.some(icon=>icon.src.includes("bithome.svg")));
assert.match(sw,/real-estate\/main.js/);
assert.match(read("docs/BITHOME-FUSION-LIGHT.md"),/trust boundaries|límites de confianza/i);
console.log("Bithome Fusion Light static architecture checks: OK");
