import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const root=path.resolve(new URL("..",import.meta.url).pathname);
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
const schema=fs.readFileSync(path.join(root,"app","schema.js"),"utf8");
const engine=fs.readFileSync(path.join(root,"app","engine.js"),"utf8");
const ui=fs.readFileSync(path.join(root,"app","ui.js"),"utf8");
const main=fs.readFileSync(path.join(root,"app","main.js"),"utf8");
const css=fs.readFileSync(path.join(root,"styles","world-ui.css"),"utf8");
const verify=fs.readFileSync(path.join(root,"verify.html"),"utf8");
const manifest=JSON.parse(fs.readFileSync(path.join(root,"manifest.webmanifest"),"utf8"));
assert.match(index,/app\/main\.js/);
assert.match(index,/world-ui\.css/);
assert.match(index,/manifest\.webmanifest/);
assert.doesNotMatch(index,/user-scalable\s*=\s*["']no["']/i);
assert.equal((schema.match(/F\("/g)||[]).length>=70,true);
assert.match(schema,/OPTIMIZATIONS/);
assert.match(engine,/crypto\.subtle/);
assert.match(engine,/publicData/);
const localSave = engine.slice(engine.indexOf("export function saveLocal"), engine.indexOf("export function restore"));
assert.match(localSave,/documentCount:state\\.docs\\.length/);
assert.doesNotMatch(localSave,/documentManifest\\(\\)/);
assert.match(engine,/integrityData/);
assert.match(engine,/URL\.revokeObjectURL/);
assert.match(engine,/RISK_MAP/);
assert.match(ui,/world-hero|summary-card/);
assert.match(main,/new window\.QRCode/);
assert.match(main,/PublicKeyCredential/);
assert.match(main,/protectiveGate/);
assert.doesNotMatch(main,/ownership|confinement/i);
assert.match(css,/world-nav/);
assert.match(css,/prefers-reduced-motion/);
assert.match(verify,/SHA-256/);
assert.match(verify,/Request ID/);
assert.equal(manifest.display,"standalone");
console.log("Contract Engine 100 smoke tests: OK");