import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const root=path.resolve(new URL("..",import.meta.url).pathname);
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
const schema=fs.readFileSync(path.join(root,"app","schema.js"),"utf8");
const engine=fs.readFileSync(path.join(root,"app","engine.js"),"utf8");
const ui=fs.readFileSync(path.join(root,"app","ui.js"),"utf8");
const main=fs.readFileSync(path.join(root,"app","main.js"),"utf8");
const css=fs.readFileSync(path.join(root,"styles","world-ui.css"),"utf8");
const verify=fs.readFileSync(path.join(root,"verify.html"),"utf8");
const manifest=JSON.parse(fs.readFileSync(path.join(root,"manifest.webmanifest"),"utf8"));
assert.match(index,/app\/main\.js/);
assert.match(index,/world-ui\.css/);
assert.match(index,/manifest\.webmanifest/);
assert.doesNotMatch(index,/user-scalable\s*=\s*["']no["']/i);
assert.equal((schema.match(/F\("/g)||[]).length>=70,true);
assert.match(schema,/Spain LAU rules engine/);
assert.match(schema,/tensionedZone/);
assert.match(schema,/largeHolder/);
assert.match(engine,/crypto\.subtle/);
assert.match(engine,/publicData/);
assert.match(engine,/integrityData/);
assert.match(engine,/documentManifest/);
assert.match(engine,/additionalGuaranteeMonths/);
assert.match(engine,/agencyFees/);
assert.match(engine,/rentComplianceEvidence/);
assert.match(ui,/summary-card/);
assert.match(main,/createSignatureRequest/);
assert.doesNotMatch(main,/workerPassport|workerNationalID|residenceDocument/);
assert.match(css,/world-nav/);
assert.match(css,/prefers-reduced-motion/);
assert.match(verify,/SHA-256/);
assert.match(verify,/Request ID/);
assert.equal(manifest.display,"standalone");
console.log("Spain Housing Rental smoke tests: OK");
