export const VERSION="6.0.0";
export const MAX_FILE_BYTES=10*1024*1024;
const opts=a=>a.map(x=>({value:x[0],label:x[1]}));
export const COUNTRIES=[["ES","España","EUR"],["FR","Francia","EUR"],["PT","Portugal","EUR"],["IT","Italia","EUR"],["DE","Alemania","EUR"],["OTHER","Otro país","EUR"]];
export const languages=opts([["es","Español"],["ca","Catalán"],["eu","Euskera"],["gl","Gallego"],["en","Inglés"],["fr","Francés"],["ar","Árabe"]]);
export const yesNo=opts([["yes","Sí"],["no","No"],["unsure","No estoy seguro/a"]]);
const F=(id,section,label,type,o={})=>({id,section,label,type,actor:o.actor||["tenant","landlord","reviewer"],required:!!o.required,private:!!o.private,restricted:!!o.restricted,when:o.when||(()=>true),options:o.options||[]});
export const SCHEMA=[
F("actor","Contexto","Quién completa el expediente","radio",{required:true,options:opts([["tenant","Arrendatario/a"],["landlord","Arrendador/a"],["reviewer","Revisor/a"]])}),
F("rentalPurpose","Contexto","Finalidad del arrendamiento","radio",{required:true,options:opts([["habitual","Vivienda habitual"],["seasonal","Temporada"],["other","Otra finalidad legalmente admisible"]])}),
F("contractForm","Contexto","Tipo de operación","radio",{required:true,options:opts([["new","Nuevo contrato"],["renewal","Renovación"],["novation","Novación"]])}),
F("province","Inmueble","Provincia","text",{required:true}),F("municipality","Inmueble","Municipio","text",{required:true}),F("postalCode","Inmueble","Código postal","text",{required:true}),F("propertyAddress","Inmueble","Dirección de la vivienda","textarea",{required:true,private:true}),F("propertyType","Inmueble","Tipo de vivienda","select",{required:true,options:opts([["flat","Piso"],["house","Casa"],["studio","Estudio"],["other","Otra"]])}),F("usableArea","Inmueble","Superficie útil aproximada (m²)","number",{required:true}),F("rooms","Inmueble","Número de habitaciones","number",{required:true}),F("bathrooms","Inmueble","Número de baños","number",{required:true}),F("furnished","Inmueble","Amueblada","switch"),F("parking","Inmueble","Plaza de aparcamiento","switch"),F("storage","Inmueble","Trastero","switch"),F("energyCertificate","Inmueble","Certificado de eficiencia energética aportado","checkbox"),F("habitabilityDocument","Inmueble","Cédula/licencia o documento equivalente aportado cuando proceda","checkbox"),F("inventory","Inmueble","Inventario y estado de conservación","textarea"),F("communityRules","Inmueble","Normas de comunidad relevantes comunicadas","textarea"),
F("landlordName","Partes","Nombre completo del arrendador/a","text",{required:true}),F("landlordId","Partes","DNI/NIE/CIF u otro identificador","text",{required:true,restricted:true}),F("landlordIsCompany","Partes","El arrendador es persona jurídica","switch"),F("landlordLargeHolder","Partes","¿Es gran tenedor conforme al régimen aplicable?","radio",{required:true,options:yesNo}),F("tenantName","Partes","Nombre completo del arrendatario/a","text",{required:true,private:true}),F("tenantId","Partes","DNI/NIE/pasaporte u otro identificador","text",{required:true,restricted:true}),F("tenantEmail","Contacto","Correo electrónico","text",{required:true,private:true}),F("tenantPhone","Contacto","Teléfono","text",{private:true}),F("tenantNationality","Partes","Nacionalidad","select",{options:COUNTRIES.map(x=>({value:x[0],label:x[1]}))}),F("occupants","Partes","Personas ocupantes previstas","number",{required:true}),F("minors","Partes","Menores de edad ocupantes","number"),F("pets","Partes","Animales de compañía","textarea"),
F("startDate","Duración","Fecha de inicio","date",{required:true}),F("agreedDurationYears","Duración","Duración inicial pactada (años)","number",{required:true}),F("endDate","Duración","Fecha de finalización pactada","date"),F("nonRenewalNoticeDays","Duración","Antelación prevista para comunicar no renovación","number"),F("needLandlordRecovery","Duración","Se incorpora pacto válido sobre recuperación por necesidad del arrendador","checkbox",{actor:["landlord","reviewer"]}),
F("rentAmount","Renta","Renta mensual pactada (€)","number",{required:true}),F("previousRent","Renta","Última renta vigente en la vivienda cuando proceda (€)","number"),F("previousContractDate","Renta","Fecha del contrato anterior cuando proceda","date"),F("referenceRent","Renta","Límite/precio de referencia aplicable cuando proceda (€)","number"),F("rentIndex","Renta","Índice/metodología de actualización pactada","select",{required:true,options:opts([["irav","IRAV / índice legal vigente"],["none","Sin actualización"],["other","Otra metodología documentada"]])}),F("tensionedZone","Renta","La vivienda está en zona de mercado residencial tensionado","switch",{required:true}),F("largeHolder","Renta","El arrendador es gran tenedor a efectos de limitación de renta","switch",{required:true}),F("rentCapBasis","Renta","Base utilizada para comprobar el límite de renta","select",{when:d=>d.tensionedZone===true,options:opts([["previous_contract","Contrato anterior"],["reference_index","Sistema de índices de referencia"],["combined","Ambos / el más restrictivo aplicable"],["na","No aplicable"]])}),F("rentComplianceEvidence","Renta","Evidencia documental de la renta/límite aplicable","textarea",{when:d=>d.tensionedZone===true}),
F("paymentDay","Pagos","Día o periodo de pago mensual","text",{required:true}),F("paymentMethod","Pagos","Medio de pago","select",{required:true,options:opts([["bank","Transferencia bancaria"],["other_electronic","Otro medio electrónico permitido"],["cash_exception","Metálico en supuesto legal excepcional"]])}),F("receiptMethod","Pagos","Sistema de justificante/recibo","textarea",{required:true}),
F("depositMonths","Garantías","Fianza legal (mensualidades)","number",{required:true}),F("additionalGuaranteeMonths","Garantías","Garantía adicional (mensualidades)","number",{required:true}),F("guaranteeType","Garantías","Tipo de garantía adicional","select",{options:opts([["none","Ninguna"],["deposit","Depósito"],["surety","Aval/garantía personal"],["insurance","Seguro de impago"],["other","Otra"]])}),F("agencyFees","Gastos","Gastos de gestión/formalización inmobiliaria","number"),F("tenantOptionalServices","Gastos","Servicios opcionales solicitados expresamente por el arrendatario","textarea",{private:true}),F("communityFees","Gastos","Gastos generales/tributos repercutidos al arrendatario","number"),F("communityFeesAnnualAmount","Gastos","Importe anual de gastos repercutidos (€)","number"),F("utilities","Gastos","Suministros y servicios individualizados","textarea"),
F("repairsMaintenance","Conservación","Reparto de reparaciones menores y mantenimiento","textarea"),F("landlordMajorRepairs","Conservación","Canal para reparaciones a cargo del arrendador","textarea"),F("accessForRepairs","Conservación","Procedimiento de acceso para obras/reparaciones","textarea"),F("subletting","Uso","Cesión/subarriendo","select",{required:true,options:opts([["no","No permitido salvo consentimiento legalmente exigible"],["partial","Solo parcial y con consentimiento escrito cuando proceda"],["other","Otro supuesto autorizado"]])}),F("works","Uso","Obras o modificaciones del arrendatario","textarea"),F("habitualResidence","Uso","La vivienda se destina a residencia habitual","checkbox",{required:true}),F("touristUse","Uso","Se prevé uso turístico","switch",{required:true}),F("petsAllowed","Uso","Régimen pactado sobre animales","textarea"),F("smoking","Uso","Régimen pactado sobre tabaco","textarea"),F("insurance","Uso","Seguro vinculado a la vivienda","textarea"),
F("privacyNotice","Privacidad","Información sobre tratamiento de datos personales entregada","checkbox",{required:true}),F("documentsComplete","Privacidad","Documentación esencial revisada","checkbox",{required:true}),F("independentReview","Revisión","Se solicita revisión independiente antes de firmar","checkbox"),F("tenantComprehension","Revisión","El arrendatario comprende las condiciones o dispone de asistencia","checkbox",{actor:["tenant"],required:true,private:true}),F("tenantIndependentCopy","Revisión","El arrendatario dispone de copia independiente","checkbox",{actor:["tenant"],required:true,private:true}),F("disputeProcedure","Revisión","Canal para incidencias y controversias","textarea"),F("signatureMethod","Firma","Método previsto de firma","select",{required:true,options:opts([["in_person","Firma presencial"],["electronic","Firma electrónica con proveedor"],["other","Otro método válido"]])}),F("identityVerification","Firma","Método de identificación/verificación","select",{required:true,options:opts([["none","Sin verificación adicional"],["dni_nie","Documento + comprobaciones"],["webauthn","WebAuthn / identidad digital compatible"],["provider","Proveedor externo"]])})
];
export const RISK_MAP=[["tensionedZone","Zona de mercado residencial tensionado",1],["largeHolder","Arrendador gran tenedor",1],["documentsComplete","Documentación incompleta",2],["rentComplianceEvidence","Falta evidencia del límite de renta cuando procede",2]];
export const OPTIMIZATIONS=[
"Progressive disclosure","Role-aware workflow","Spain LAU rules engine","Tensioned-zone gate","Large-holder gate","Rent-cap evidence","IRAV-aware update option","Fianza calculator","Additional-guarantee cap check","Agency-fee guardrail","Electronic-payment default","Receipt traceability","Inventory protocol","Habitability documentation","Energy certificate checkpoint","Community-cost annualization","Individualized-utility allocation","Repair workflow","Access notice workflow","Sublease control","Residence-purpose control","Tourist-use conflict gate","Pets policy","Data minimization","Private PII segregation","Restricted ID segregation","Document SHA-256","Contract SHA-256","Snapshot versioning","Contract Diff","Audit trail","QR minimization","Static verification","Server verification ready","WebAuthn ready","Provider-neutral signature layer","No fake signature","No fake identity","Human review gate","Non-discrimination check","Legal-source traceability","Dynamic legal policy versioning","Province/municipality context","Tensioned-zone evidence","Rent benchmark evidence","Payment schedule validation","Date validation","Guarantee validation","Annual-cost validation","Party identity validation","Occupancy validation","Maintenance responsibility","Dispute workflow","Copy delivery checkpoint","Consent matrix","PWA","iPhone-first","VoiceOver","Reduced motion","Dynamic Type","High contrast","Dark mode","Bottom navigation","Quick actions","Expert mode","Audit export","Document manifest","Object URL cleanup","Autosave","Draft recovery","Risk explanation","Evidence-first validation","Rule provenance","Policy change alerts","Jurisdiction lock","Contract completeness score","Tenant fairness panel","Landlord compliance panel","Pre-signing blockers","Post-edit draft reset","Canonical serialization","Integrity hash","Verification URL","Data retention policy hook","Deletion workflow hook","Role authorization hook","Backend adapter","Signature webhook adapter","Identity webhook adapter","PDF contract generation hook","Document package hook","Timeline","Renewal calendar hook","Rent update calculator hook","Issue log","Escalation workflow","Legal-review handoff","Accessibility audit hook","Security headers hook","CSP readiness","Dependency pinning","Test fixtures","Property-based rule tests"];
