export const VERSION="6.1.0";
export const MAX_FILE_BYTES=10*1024*1024;
const opts=a=>a.map(x=>({value:x[0],label:x[1]}));
export const PROVINCES=["Álava","Albacete","Alicante","Almería","Asturias","Ávila","Badajoz","Barcelona","Bizkaia","Burgos","Cáceres","Cádiz","Cantabria","Castellón","Ceuta","Ciudad Real","Córdoba","Cuenca","Gipuzkoa","Girona","Granada","Guadalajara","Huelva","Huesca","Illes Balears","Jaén","La Coruña","La Rioja","Las Palmas","León","Lleida","Lugo","Madrid","Málaga","Melilla","Murcia","Navarra","Ourense","Palencia","Pontevedra","Salamanca","Santa Cruz de Tenerife","Segovia","Sevilla","Soria","Tarragona","Teruel","Toledo","Valencia","Valladolid","Zamora","Zaragoza"];
export const COUNTRIES=[["ES","España","EUR"],["FR","Francia","EUR"],["PT","Portugal","EUR"],["IT","Italia","EUR"],["DE","Alemania","EUR"],["OTHER","Otro país","EUR"]];
export const languages=opts([["es","Español"],["ca","Catalán"],["eu","Euskera"],["gl","Gallego"],["en","Inglés"],["fr","Francés"],["ar","Árabe"]]);
export const yesNo=opts([["yes","Sí"],["no","No"],["unsure","No estoy seguro/a"]]);
const F=(id,section,label,type,o={})=>({id,section,label,type,actor:o.actor||["tenant","landlord","reviewer"],required:!!o.required,private:!!o.private,restricted:!!o.restricted,computed:!!o.computed,when:o.when||(()=>true),options:o.options||[]});
export const SCHEMA=[
F("actor","Contexto","Quién completa el expediente","radio",{required:true,options:opts([["tenant","Arrendatario/a"],["landlord","Arrendador/a"],["reviewer","Revisor/a"]])}),
F("rentalPurpose","Contexto","Finalidad del arrendamiento","radio",{required:true,options:opts([["habitual","Vivienda habitual"],["seasonal","Temporada"],["other","Otra finalidad legalmente admisible"]])}),
F("contractForm","Contexto","Tipo de operación","radio",{required:true,options:opts([["new","Nuevo contrato"],["renewal","Renovación"],["novation","Novación"]])}),
F("seasonalReason","Contexto","Causa concreta de temporalidad","textarea",{when:d=>d.rentalPurpose==="seasonal",required:true}),
F("province","Inmueble","Provincia","select",{required:true,options:PROVINCES.map(x=>({value:x,label:x}))}),
F("municipality","Inmueble","Municipio","text",{required:true}),
F("postalCode","Inmueble","Código postal","text",{required:true}),
F("propertyAddress","Inmueble","Dirección de la vivienda","textarea",{required:true,private:true}),
F("propertyType","Inmueble","Tipo de vivienda","select",{required:true,options:opts([["flat","Piso"],["house","Casa"],["studio","Estudio"],["other","Otra"]])}),
F("usableArea","Inmueble","Superficie útil aproximada (m²)","number",{required:true}),
F("rooms","Inmueble","Número de habitaciones","number",{required:true}),
F("bathrooms","Inmueble","Número de baños","number",{required:true}),
F("furnished","Inmueble","Amueblada","switch"),F("parking","Inmueble","Plaza de aparcamiento","switch"),F("storage","Inmueble","Trastero","switch"),
F("protectedHousing","Inmueble","Vivienda protegida","switch"),F("newBuildOrMajorRehab","Inmueble","Obra nueva o gran rehabilitación relevante","switch"),
F("energyCertificate","Inmueble","Certificado de eficiencia energética aportado","checkbox"),
F("habitabilityDocument","Inmueble","Cédula/licencia o documento equivalente aportado cuando proceda","checkbox"),
F("inventory","Inmueble","Inventario y estado de conservación","textarea"),
F("communityRules","Inmueble","Normas de comunidad relevantes comunicadas","textarea"),
F("propertySupportingDocs","Inmueble","Documentación adicional del inmueble","files"),
F("landlordName","Partes","Nombre completo del arrendador/a","text",{required:true}),
F("landlordId","Partes","DNI/NIE/CIF u otro identificador","text",{required:true,restricted:true}),
F("landlordIsCompany","Partes","El arrendador es persona jurídica","switch"),
F("landlordLargeHolder","Partes","¿Es gran tenedor conforme al régimen aplicable?","radio",{required:true,options:yesNo}),
F("tenantName","Partes","Nombre completo del arrendatario/a","text",{required:true,private:true}),
F("tenantId","Partes","DNI/NIE/pasaporte u otro identificador","text",{required:true,restricted:true}),
F("tenantEmail","Contacto","Correo electrónico","text",{required:true,private:true}),F("tenantPhone","Contacto","Teléfono","text",{private:true}),
F("tenantNationality","Partes","Nacionalidad","select",{options:COUNTRIES.map(x=>({value:x[0],label:x[1]}))}),
F("occupants","Partes","Personas ocupantes previstas","number",{required:true}),F("minors","Partes","Menores de edad ocupantes","number"),F("pets","Partes","Animales de compañía","textarea"),
F("startDate","Duración","Fecha de inicio","date",{required:true}),
F("agreedDurationYears","Duración","Duración inicial pactada (años)","number",{required:true}),
F("endDate","Duración","Fecha de finalización pactada","date"),
F("nonRenewalNoticeDays","Duración","Antelación prevista para comunicar no renovación","number"),
F("needLandlordRecovery","Duración","Se incorpora pacto sobre recuperación por necesidad del arrendador","checkbox",{actor:["landlord","reviewer"]}),
F("rentAmount","Renta","Renta mensual pactada (€)","number",{required:true}),
F("previousRent","Renta","Última renta vigente cuando proceda (€)","number"),
F("previousContractDate","Renta","Fecha del contrato anterior cuando proceda","date"),
F("priorLeaseWithinFiveYears","Renta","Hubo contrato residencial vigente en los últimos 5 años","radio",{required:true,options:opts([["yes","Sí"],["no","No"],["unknown","No acreditado"]])}),
F("previousRentEvidence","Renta","Evidencia de la renta anterior","files"),
F("referenceRent","Renta","Límite/precio de referencia aplicable (€)","number"),
F("referenceRentEvidence","Renta","Evidencia del índice/límite de referencia","files"),
F("rentIndex","Renta","Índice/metodología de actualización pactada","select",{required:true,options:opts([["irav","IRAV / índice legal vigente cuando proceda"],["none","Sin actualización"],["other","Otra metodología documentada"]])}),
F("tensionedZone","Renta","Zona de mercado residencial tensionado detectada","switch",{computed:true}),
F("largeHolder","Renta","Gran tenedor a efectos de limitación de renta","switch",{computed:true}),
F("tensionDeclarationEvidence","Renta","Evidencia de declaración y vigencia de la zona","files"),
F("rentCapBasis","Renta","Base utilizada para comprobar el límite de renta","select",{when:d=>d.tensionedZone===true,options:opts([["previous_contract","Contrato anterior"],["reference_index","Sistema de índices de referencia"],["combined","Ambos / el más restrictivo aplicable"],["na","No aplicable"]])}),
F("rentComplianceEvidence","Renta","Explicación/evidencia del cumplimiento del límite","textarea",{when:d=>d.tensionedZone===true}),
F("paymentDay","Pagos","Día o periodo de pago mensual","text",{required:true}),
F("paymentMethod","Pagos","Medio de pago","select",{required:true,options:opts([["bank","Transferencia bancaria"],["other_electronic","Otro medio electrónico permitido"],["cash_exception","Metálico en supuesto legal excepcional"]])}),
F("receiptMethod","Pagos","Sistema de justificante/recibo","textarea",{required:true}),
F("depositMonths","Garantías","Fianza legal (mensualidades)","number",{required:true}),
F("additionalGuaranteeMonths","Garantía","Garantía adicional (mensualidades)","number",{required:true}),
F("guaranteeType","Garantía","Tipo de garantía adicional","select",{options:opts([["none","Ninguna"],["deposit","Depósito"],["surety","Aval/garantía personal"],["insurance","Seguro de impago"],["other","Otra"]])}),
F("agencyFees","Gastos","Gastos de gestión/formalización inmobiliaria repercutidos","number"),
F("tenantOptionalServices","Gastos","Servicios opcionales solicitados expresamente por el arrendatario","textarea",{private:true}),
F("communityFees","Gastos","Gastos generales/tributos repercutidos al arrendatario","number"),
F("communityFeesAnnualAmount","Gastos","Importe anual de gastos repercutidos (€)","number"),
F("utilities","Gastos","Suministros y servicios individualizados","textarea"),
F("repairsMaintenance","Conservación","Reparto de reparaciones menores y mantenimiento","textarea"),
F("landlordMajorRepairs","Conservación","Canal para reparaciones a cargo del arrendador","textarea"),
F("accessForRepairs","Conservación","Procedimiento de acceso para obras/reparaciones","textarea"),
F("subletting","Uso","Cesión/subarriendo","select",{required:true,options:opts([["no","No permitido salvo consentimiento legalmente exigible"],["partial","Solo parcial y con consentimiento escrito cuando proceda"],["other","Otro supuesto autorizado"]])}),
F("works","Uso","Obras o modificaciones del arrendatario","textarea"),
F("habitualResidence","Uso","La vivienda se destina a residencia habitual","checkbox",{when:d=>d.rentalPurpose==="habitual",required:true}),
F("touristUse","Uso","Se prevé uso turístico","switch",{required:true}),
F("petsAllowed","Uso","Régimen pactado sobre animales","textarea"),F("smoking","Uso","Régimen pactado sobre tabaco","textarea"),F("insurance","Uso","Seguro vinculado a la vivienda","textarea"),
F("privacyNotice","Privacidad","Información sobre tratamiento de datos personales entregada","checkbox",{required:true}),
F("documentsComplete","Privacidad","Documentación esencial revisada","checkbox",{required:true}),
F("independentReview","Revisión","Se solicita revisión independiente antes de firmar","checkbox"),
F("tenantComprehension","Revisión","El arrendatario comprende las condiciones o dispone de asistencia","checkbox",{actor:["tenant"],required:true,private:true}),
F("tenantIndependentCopy","Revisión","El arrendatario dispone de copia independiente","checkbox",{actor:["tenant"],required:true,private:true}),
F("disputeProcedure","Revisión","Canal para incidencias y controversias","textarea"),
F("documentPack","Revisión","Paquete final de contrato/anexos/evidencias","files"),
F("signatureMethod","Firma","Método previsto de firma","select",{required:true,options:opts([["in_person","Firma presencial"],["electronic","Firma electrónica con proveedor"],["other","Otro método válido"]])}),
F("identityVerification","Firma","Método de identificación/verificación","select",{required:true,options:opts([["none","Sin verificación adicional"],["dni_nie","Documento + comprobaciones"],["webauthn","WebAuthn / identidad digital compatible"],["provider","Proveedor externo"]])})
];
export const RISK_MAP=[["documentsComplete","Documentación incompleta",2],["rentComplianceEvidence","Falta explicación del cumplimiento de renta cuando procede",2],["tensionedZone","Zona de mercado residencial tensionado",1],["largeHolder","Gran tenedor",1],["priorLeaseWithinFiveYears","Antecedentes de renta no acreditados",1]];
export const OPTIMIZATIONS=[
"Wizard contractual de 5 etapas","Motor declarativo de cláusulas","Perfil reutilizable de arrendador","Perfil reutilizable de arrendatario","contractId permanente","Versionado semántico","Timeline contractual","Estados DRAFT/REVIEW/PENDING_SIGNATURE/SIGNED/ACTIVE/FINALIZED","Navegación por tareas pendientes","Score de completitud",
"Motor de reglas LAU España","Selector vivienda habitual/temporada","Detección de supuestos especiales","Reglas por comunidad/provincia/municipio","Control de zona tensionada","Gran tenedor contextual","Evidencia de renta anterior","Evidencia de índice de referencia","Proveniencia de cada regla","Fecha de vigencia de política","Explicación de regla activada","Evidencia faltante como tarea","Separación regla/dato/evidencia/cálculo/revisión","Detector de contradicciones","Detector de cláusulas ambiguas","Trazabilidad campo→regla→cláusula→documento",
"Calculadora de renta","Cálculo anual","Coste total de ocupación","Fianza","Garantía adicional","Límites configurables","Desglose de renta/gastos/suministros","Historial de renta","Actualización futura","Escenarios de renovación","Comparación con renta previa","Detector de variación sospechosa","Timestamp económico","Gastos anualizados","Servicios opcionales","Panel de coste real","Alertas matemáticas","Exportación económica",
"Ficha estructurada del inmueble","Dirección normalizada","CP","Catálogo provincial","Superficie","Habitaciones/baños","Amueblado","Aparcamiento/trastero","Inventario","Estado por estancia","Fotos entrada/salida","Hash de fotos","Comparación de fotos","Electrodomésticos","Contadores","Lecturas de contadores","Daños preexistentes","Anexo inventario","Habitabilidad/energía","ID interno del inmueble",
"Panel de equidad","Detector de discriminación","No puntuar atributos sensibles","Comprobaciones transparentes","Botón no entiendo la cláusula","Lectura en voz alta","Resumen lenguaje claro","Modo explicación jurídica","Confirmación de comprensión","Copia independiente","Clasificación documental","SHA-256 de cada documento","Manifest documental","Versionado documental","Detector de documento sustituido","Detector de vencimiento","OCR preparado","Cruce documento/formulario","Alerta de identidad","Paquete contractual",
"Preparación de firma","WebAuthn backend-ready","Firma electrónica proveedor-neutral","Registro de actor/acción","Auditoría backend-ready","QR mínimo","Verificación servidor-ready","Página pública de verificación","Firma ligada a versión","Retención/borrado","Adaptador backend","Adaptador firma","Adaptador identidad","Hook PDF","Hook paquete","Hook calendario","Hook actualización renta","Issue log","Escalado legal","CSP/security headers","Dependencias fijadas","Tests de reglas","Property-based tests"
];
