/*
 * Contract Engine 100 · Field System
 * Copyright (c) 2026 Alejandro Hernández Castillo
 * Contact: acastilloalejandro@icloud.com
 * License: see LICENSE and NOTICE.md at the repository root.
 * Third-party components, dependencies, and assets remain under their own licenses.
 */
export const VERSION="5.2.1";
export const MAX_FILE_BYTES=10*1024*1024;
export const DAYS=["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"];
export const COUNTRIES=[["SA","Arabia Saudí","SAR"],["ES","España","EUR"],["FR","Francia","EUR"],["PH","Filipinas","PHP"],["IN","India","INR"],["ID","Indonesia","IDR"]];
const opts=a=>a.map(x=>({value:x[0],label:x[1]}));
export const languages=opts([["es","Español"],["ar","Árabe"],["en","Inglés"],["fr","Francés"],["tl","Tagalog"],["id","Indonesio"],["hi","Hindi"]]);
export const yesNo=opts([["yes","Sí"],["no","No"],["unsure","No estoy seguro/a"],["limited","Limitado"]]);
const F=(id,section,label,type,o={})=>({id,section,label,type,actor:o.actor||["worker","employer"],required:!!o.required,private:!!o.private,restricted:!!o.restricted,when:o.when||(()=>true),options:o.options||[]});
export const SCHEMA=[
F("workerRole","Contexto","Quién completa el expediente","radio",{required:true,options:opts([["worker","Trabajador/a"],["employer","Empleador/a"],["reviewer","Revisor/a"]])}),
F("relationshipType","Contexto","Tipo de relación laboral","select",{required:true,options:opts([["domestic_employment","Trabajo doméstico"],["personal_assistant","Asistente personal"],["private_driver","Conductor/a privado/a"],["cook","Cocinero/a"],["caregiver","Cuidador/a"],["other","Otro puesto autorizado"]])}),
F("country","Contexto","País principal","select",{required:true,options:COUNTRIES.map(x=>({value:x[0],label:x[1]}))}),F("city","Contexto","Ciudad principal","text",{required:true}),F("jurisdiction","Contexto","Jurisdicción o marco aplicable","text",{required:true}),
F("workerFullName","Partes","Nombre completo del trabajador/a","text",{required:true,private:true}),F("workerDateOfBirth","Partes","Fecha de nacimiento","date",{required:true,private:true}),F("workerNationality","Partes","Nacionalidad","select",{required:true,private:true,options:COUNTRIES.map(x=>({value:x[0],label:x[1]}))}),
F("workerEmail","Contacto","Correo electrónico","text",{required:true,private:true}),F("workerPhone","Contacto","Teléfono","text",{required:true,private:true}),F("emergencyContact","Contacto","Contacto de emergencia","textarea",{private:true}),
F("employerFullName","Partes","Nombre completo del empleador/a","text",{required:true,private:true}),F("employerNationality","Partes","Nacionalidad del empleador/a","select",{required:true,private:true,options:COUNTRIES.map(x=>({value:x[0],label:x[1]}))}),F("employerIdNumber","Partes","Identificador nacional o residencia","text",{required:true,restricted:true}),
F("workerPreferredLanguage","Derechos","Idioma preferido","select",{actor:["worker"],options:languages}),F("contractLanguage","Derechos","Idioma del contrato","select",{required:true,options:languages}),F("interpreterRequired","Derechos","Necesita intérprete o asistencia lingüística","switch",{actor:["worker"],private:true}),
F("workerUnderstandsContract","Derechos","Comprendo el contrato o he solicitado asistencia independiente","checkbox",{actor:["worker"],private:true}),F("workerIndependentCopy","Derechos","Tengo acceso a una copia independiente del contrato","checkbox",{actor:["worker"],private:true}),
F("workerCanContactFamily","Protección","Puedo contactar con familiares o personas de confianza","radio",{actor:["worker"],private:true,options:yesNo}),F("workerHasPhoneAccess","Protección","Tengo acceso privado a un medio de comunicación","radio",{actor:["worker"],private:true,options:yesNo}),
F("workerCanLeaveSite","Protección","Puedo salir del lugar de trabajo cuando no estoy trabajando","radio",{actor:["worker"],private:true,options:yesNo}),F("workerDocumentAccess","Protección","Tengo acceso personal a mis documentos","radio",{actor:["worker"],private:true,options:yesNo}),
F("workerRecruitmentDeception","Protección","Las condiciones coinciden con lo prometido al contratar","radio",{actor:["worker"],private:true,options:yesNo}),F("workerRecruitmentDebt","Protección","Existe deuda o coste de contratación que dificulta dejar el empleo","radio",{actor:["worker"],private:true,options:yesNo}),
F("workerWageWithholding","Protección","Se han retenido salarios o pagos acordados sin razón legítima","radio",{actor:["worker"],private:true,options:yesNo}),F("workerThreats","Protección","He sufrido amenazas, intimidación o represalias","radio",{actor:["worker"],private:true,options:yesNo}),
F("workerViolence","Protección","He sufrido violencia física, sexual o psicológica relacionada con el trabajo","radio",{actor:["worker"],private:true,options:yesNo}),F("workerIsolation","Protección","Se ha limitado mi contacto con personas de confianza","radio",{actor:["worker"],private:true,options:yesNo}),
F("workerAbuseVulnerability","Protección","Una situación de vulnerabilidad está siendo utilizada para presionarme","radio",{actor:["worker"],private:true,options:yesNo}),F("workerAbusiveConditions","Protección","Las condiciones de trabajo o alojamiento son degradantes o inseguras","radio",{actor:["worker"],private:true,options:yesNo}),
F("workerExcessiveOvertime","Protección","Me obligan a realizar horas excesivas que no puedo rechazar","radio",{actor:["worker"],private:true,options:yesNo}),F("workerRestrictionMovement","Protección","Se restringen mis movimientos mediante amenazas o bloqueo","radio",{actor:["worker"],private:true,options:yesNo}),
F("position","Empleo","Puesto o función","text",{required:true}),F("dutiesDescription","Empleo","Funciones y responsabilidades","textarea",{required:true}),F("excludedDuties","Empleo","Tareas expresamente excluidas","textarea"),F("workplaceAddress","Empleo","Lugar principal de trabajo","textarea",{required:true,private:true}),F("startDate","Empleo","Fecha de inicio","date",{required:true}),F("endDate","Empleo","Fecha de finalización","date"),F("trialPeriod","Empleo","Periodo de prueba en días","number"),F("terminationNotice","Empleo","Procedimiento y preaviso de terminación","textarea"),
F("workingDays","Jornada","Días de trabajo","multiselect",{required:true,options:DAYS.map(x=>({value:x,label:x}))}),F("startTime","Jornada","Hora de inicio","time",{required:true}),F("endTime","Jornada","Hora de finalización","time",{required:true}),F("breaks","Jornada","Pausas previstas","textarea"),F("weeklyRestDay","Jornada","Día principal de descanso semanal","select",{required:true,options:DAYS.map(x=>({value:x,label:x}))}),F("overtimePolicy","Jornada","Condiciones para horas adicionales y compensación","textarea"),
F("compensation","Remuneración","Remuneración","radio",{required:true,options:opts([["paid","Remunerada"],["unpaid","No remunerada"]])}),F("salaryAmount","Remuneración","Importe acordado","number",{required:true,private:true,when:d=>d.compensation==="paid"}),F("currency","Remuneración","Moneda","select",{required:true,when:d=>d.compensation==="paid",options:opts([["SAR","SAR · Riyal saudí"],["EUR","EUR · Euro"],["PHP","PHP · Peso filipino"],["INR","INR · Rupia india"],["IDR","IDR · Rupia indonesia"],["USD","USD · Dólar estadounidense"]])}),F("paymentFrequency","Remuneración","Frecuencia de pago","select",{required:true,when:d=>d.compensation==="paid",options:opts([["monthly","Mensual"],["weekly","Semanal"],["other","Otra periodicidad acordada"]])}),F("paymentMethod","Remuneración","Método de pago","select",{required:true,when:d=>d.compensation==="paid",options:opts([["bank_transfer","Transferencia bancaria"],["other_authorized","Otro método permitido"]])}),F("recruitmentFee","Remuneración","Coste o comisión de contratación pagado por el trabajador","number",{actor:["worker"],private:true}),F("wageDeductions","Remuneración","Deducciones periódicas registradas","number"),F("deductionExplanation","Remuneración","Explicación de las deducciones","textarea",{when:d=>Number(d.wageDeductions||0)>0}),F("paymentHistory","Remuneración","Registro resumido de pagos o incidencias","textarea",{private:true}),
F("liveIn","Alojamiento","Se proporciona alojamiento","switch"),F("accommodationDetails","Alojamiento","Detalles del alojamiento","textarea",{required:true,when:d=>d.liveIn===true}),F("housingSafety","Alojamiento","Seguridad y privacidad del alojamiento","textarea"),
F("travelRequired","Viajes","Se prevén desplazamientos por trabajo","switch"),F("travelDetails","Viajes","Destinos, frecuencia y gastos","textarea",{required:true,when:d=>d.travelRequired===true}),F("travelExpenses","Viajes","Quién cubre los gastos y cómo se documentan","textarea"),
F("workerPassport","Documentos","Pasaporte","file",{required:true,restricted:true}),F("workerNationalID","Documentos","Documento nacional de identidad","file",{restricted:true}),F("residenceDocument","Documentos","Documento de residencia o permiso","file",{restricted:true}),F("additionalDocuments","Documentos","Otros documentos y anexos","files",{private:true}),
F("nda","Confidencialidad","Existe acuerdo de confidencialidad","switch"),F("ndaTerms","Confidencialidad","Alcance de la confidencialidad","textarea",{required:true,when:d=>d.nda===true}),
F("disputeMechanism","Derechos","Mecanismo para dudas, reclamaciones o conflictos","textarea"),F("assistanceContact","Derechos","Canal independiente de asistencia laboral","text",{actor:["worker"],private:true}),
F("independentReviewRequested","Consentimientos","Solicito revisión independiente","checkbox",{actor:["worker"],private:true}),F("privacyAcknowledgement","Consentimientos","Comprendo la separación entre respuestas privadas y QR público","checkbox",{actor:["worker"],private:true}),
F("readCompensation","Consentimientos","He revisado remuneración y pago","checkbox",{actor:["worker"]}),F("readSchedule","Consentimientos","He revisado jornada y descanso","checkbox",{actor:["worker"]}),F("workerRightsAcknowledged","Consentimientos","He leído derechos y puedo pedir explicación","checkbox",{actor:["worker"],required:true}),
F("consentIdentity","Consentimientos","Confirmo la exactitud de la identidad","checkbox",{required:true}),F("consentDocuments","Consentimientos","Confirmo la revisión documental","checkbox",{required:true}),F("consentContract","Consentimientos","Confirmo que he revisado las condiciones","checkbox",{required:true})
];
export const RISK_MAP=[["workerRecruitmentDeception","Engaño durante la contratación",2],["workerRecruitmentDebt","Deuda o coste que dificulta dejar el empleo",3],["workerWageWithholding","Retención de salarios",3],["workerThreats","Amenazas o intimidación",3],["workerViolence","Violencia",3],["workerIsolation","Aislamiento",2],["workerAbuseVulnerability","Abuso de vulnerabilidad",2],["workerAbusiveConditions","Condiciones abusivas",2],["workerExcessiveOvertime","Horas excesivas",2],["workerRestrictionMovement","Restricción de movimientos",3],["workerDocumentAccess","Acceso restringido a documentos",3],["workerCanLeaveSite","Acceso restringido al exterior",2],["workerHasPhoneAccess","Comunicación privada limitada",2],["workerCanContactFamily","Contacto familiar limitado",2]];
export const OPTIMIZATIONS=["Progressive disclosure","Mobile single-column","Contextual actions","Progress meter","Dependency graph","Role-aware rendering","Worker privacy mode","Independent review gate","Language preference","Interpreter flow","Comprehension confirmation","Independent copy","Emergency contact","Private communications","Family contact","Movement autonomy","Document access","Recruitment deception","Recruitment debt","Wage withholding","Threats","Violence","Isolation","Vulnerability","Abusive conditions","Excessive overtime","Recruitment fee","Deduction tracking","Deduction explanation","Payment history","Breaks","Overtime policy","Termination procedure","Dispute mechanism","Assistance channel","Housing safety","Travel expenses","Insurance reference","Document hashing","Document provenance","Expiry warning","Mismatch detection","Camera capture","Multi-file upload","File-size guard","Image metadata safety","PDF preview","Text reading","Read aloud","Explain field","Validation summary","Date validation","Time validation","Rest-day validation","Compensation validation","Private storage exclusion","Debounced autosave","Draft recovery","Safe areas","Dynamic Type","VoiceOver","Reduced motion","Keyboard-safe layout","Dark mode","High-contrast states","Financial-style hero","Quick action pills","Compact cards","Bottom navigation","Version snapshots","Contract diff","Canonical hashing","Stable document manifest","Audit events","Actor provenance","Sensitivity tags","QR minimization","Static verification","WebAuthn capability","No fake biometrics","No fake qualified signature","Signer gate","Post-edit draft reset","Protective hold","Error/warning separation","Human review handoff","Risk explanation","Risk not legal diagnosis","Bounded snapshots","Schema rendering","Declarative conditions","Normalized identities","Normalized contacts","Currency metadata","Country metadata","Language metadata","Timezone metadata","Document classification","Object URL cleanup","Clipboard sharing","No coercive controls"];
