export const STAGES=[{id:1,key:"property",label:"Inmueble",sections:["Contexto","Inmueble"],icon:"01"},{id:2,key:"parties",label:"Partes",sections:["Partes","Contacto","Duración"],icon:"02"},{id:3,key:"rent",label:"Renta",sections:["Renta","Pagos","Garantías","Gastos"],icon:"03"},{id:4,key:"conditions",label:"Condiciones",sections:["Conservación","Uso","Privacidad","Revisión"],icon:"04"},{id:5,key:"signature",label:"Firma",sections:["Firma"],icon:"05"}];
export const LIFECYCLE=["DRAFT","REVIEW","PENDING_SIGNATURE","SIGNED","ACTIVE","FINALIZED"];
const stageMap=new Map(STAGES.flatMap(s=>s.sections.map(section=>[section,s.id])));
export const stageForField=f=>stageMap.get(f?.section)||1;
export const stageForFieldId=(schema,id)=>stageForField(schema.find(f=>f.id===id)||{section:"Contexto"});
export const currentStage=n=>STAGES.find(s=>s.id===Number(n))||STAGES[0];
export const stageFields=(schema,data,role,stage)=>{const s=currentStage(stage);return schema.filter(f=>(!f.actor||f.actor.includes(role))&&f.when(data)&&stageMap.get(f.section)===s.id);};
export function completionForStage(fields,data){const required=fields.filter(f=>f.required);const done=required.filter(f=>{const v=data[f.id];return f.type==="checkbox"?v===true:f.type==="file"?Boolean(v?.id):v!==undefined&&v!==null&&v!==""&&!(Array.isArray(v)&&v.length===0);}).length;return{done,required:required.length,pct:required.length?Math.round(done/required.length*100):100};}
export function taskList({validation,legal,fieldsById}){const tasks=[];for(const e of validation?.errors||[])tasks.push({id:"error:"+e.field,level:"error",field:e.field,label:e.message,stage:stageForFieldId(fieldsById,e.field)});for(const w of validation?.warnings||[])tasks.push({id:"warning:"+w.field,level:"warning",field:w.field,label:w.message,stage:stageForFieldId(fieldsById,w.field)});for(const x of legal?.evidenceRequired||[])tasks.push({id:"evidence:"+x,level:"warning",field:"documentPack",label:"Aportar evidencia: "+x,stage:4});return tasks.slice(0,14);}
export const nextSemver=(version="1.0.0",level="minor")=>{const [a,b,c]=String(version).split(".").map(x=>Number(x)||0);return level==="major"?`${a+1}.0.0`:level==="patch"?`${a}.${b}.${c+1}`:`${a}.${b+1}.0`;};
export function timeline(state){const base=[{timestamp:state.createdAt||new Date().toISOString(),action:"contract.created",label:"Expediente creado"},...(state.audit||[]).map(e=>({timestamp:e.timestamp,action:e.action,label:e.action,meta:e.meta||{}}))];return base.sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)).slice(-40);}
